apiVersion: v1
kind: Pod
metadata:
  name: webapp
  #namespace: dellabeneta
  labels:
    name: webapp
spec:
  containers:
  - name: webapp
    image: registry.digitalocean.com/k8s-dellabeneta-registry/webapp:latest
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
