apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
  #namespace: dellabeneta
  labels:
    app: webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: registry.digitalocean.com/k8s-dellabeneta-registry/webapp:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

